### ISSUE TITLE
Asset code visibility in on-chain markets

### ISSUE THREAD

**Issue by goodplanets** [btdex/btdex#101]
![image](https://user-images.githubusercontent.com/40472463/88697916-f6c07280-d0ca-11ea-8861-f46dc24cec44.png)

**Comment by jjos2372** [comment]
It is fixed on the dev branch:
![image](https://user-images.githubusercontent.com/31958515/88703771-896d0b80-d0e3-11ea-8478-b13270cd221f.png)
