### ISSUE TITLE
Reuse of existing Smart Contracts

### ISSUE THREAD

**Issue by holgerkpedersen** [btdex/btdex#105]
I've created 3 Smart Contracts (SC Creation). But, today when I tried to "BUY BURST" for "BTC"; I noticed, the UI asked for creation of a new SC. My first thought was: "Where do I see the contracts?", so I found them on the TRANSACTIONS tabpage. 
![image](https://user-images.githubusercontent.com/1609665/89706112-0fe6e000-d963-11ea-80de-22bbd3eca288.png)
It's unclear why it doesn't reuse one of the three created contracts. Any thoughts on this issue?

**Comment by holgerkpedersen** [comment]
My best guess is, that the SC Creation expires; when there has been a Payment. But it should be clearly stated.

**Comment by jjos2372** [comment]
They don't expire but we have different contracts for buy and sell offers. Please let us know if this is the cause of the problem or if we need to investigate further.

**Comment by holgerkpedersen** [comment]
I tried to do 5 transactions, but only 4 was working with 5 SC Payment transactions. It asked for new contract to be made when I tried to make the 5th payment.
![image](https://user-images.githubusercontent.com/1609665/89720562-96d3a100-d9d3-11ea-93a4-2f6175a29a70.png)
Here are the Transactions
![image](https://user-images.githubusercontent.com/1609665/89720585-e0bc8700-d9d3-11ea-96ef-daa9a0d4fa34.png)

**Comment by jjos2372** [comment]
Maybe the matter if the contracts are for buy or sell Burst. We are working on this to make it more clear on the dialog for contract registration:
![img](https://cdn.discordapp.com/attachments/658988444583854080/742016356735778826/unknown.png)

**Comment by holgerkpedersen** [comment]
Old version. Will look for it in newUI. I close the issue.
