### ISSUE TITLE
Ghost transaction from TRT shows up on other markets

### ISSUE THREAD

**Issue by holgerkpedersen** [btdex/btdex#106]
I looked at the TRT and now one of the TRT transactions are showing up on all cross-chain markets as a king of ghost transaction. Seems to be a bug.
![image](https://user-images.githubusercontent.com/1609665/89720302-b1f0e180-d9d0-11ea-8c4d-2ae49d168aab.png)
Now look at the BTC or any other market
![image](https://user-images.githubusercontent.com/1609665/89720307-c7fea200-d9d0-11ea-873f-46aaee3ceb78.png)
Better look into this.

**Comment by holgerkpedersen** [comment]
I've tried to start the client app today. The ghost was gone 😄 
But, now I got stubborn. So I tried to copy the ghost link to the clipboard, and Voila. The ghost was back. This is a bug!
After copying a contract, the same will show up in all of the other markets. @jjos2372 I think it's a task for you 🙂

**Comment by jjos2372** [comment]
The button's logic was reworked on https://github.com/btdex/btdex/tree/newUI branch. If possible please check if you can reproduce it with this new code.

**Comment by jjos2372** [comment]
Recent improvements were already merged on v0.3

**Comment by holgerkpedersen** [comment]
I can't seem to reproduce on v0.3, so I close it.
