### ISSUE TITLE
One of my offers I can't remove; even if not taken

### ISSUE THREAD

**Issue by holgerkpedersen** [btdex/btdex#107]
I don't know why I can't seem to cancel it - lacking the "x" button. It's marked with yellow.  
![image](https://user-images.githubusercontent.com/1609665/89720851-f8e1d580-d9d6-11ea-8a57-7e7aad961ad3.png)
Perhaps, because it is the first transaction in the green list?

**Comment by jjos2372** [comment]
If possible, please test the https://github.com/btdex/btdex/tree/newUI branch, and let me know. We had some improvements there.

**Comment by holgerkpedersen** [comment]
It wasn't mine in the first place. I just thought it was. Closing thie issue 😄
