### ISSUE TITLE
Improved Labelling of Buy/Sell Smart Contracts

### ISSUE THREAD

**Issue by Tek-Mind** [btdex/btdex#108]
There should be a more intuitive way for users to determine if a smart contract (SC) they created is a BUY order or a SELL order. One possible solution recommended by jjos (Discord August 2020) is to change the name of the SC from “BTDEX” to either “BTDEX-BUY” or “BTDEX-SELL”. Then users can simply review their SCs in an explorer (see reference screenshot below).

Reference: https://explorer.burstcoin.network/?action=ats
![C7E17966-A7E8-4345-91DC-56186ACD8BF0](https://user-images.githubusercontent.com/63327640/89733186-c0b3b480-da21-11ea-99be-0c195102c497.jpeg)

**Comment by jjos2372** [comment]
This is implemented on https://github.com/btdex/btdex/tree/newUI branch. Should be available on the next release.

**Comment by jjos2372** [comment]
Already merged on v0.3
