### ISSUE TITLE
Cannot De-list Token/Burst Pairs From UI

### ISSUE THREAD

**Issue by Nivok-Spilkommen** [btdex/btdex#111]
The UI allows the addition of token pairs but not the deletion of any token pair.  Editing the config file is required.

**Comment by Nivok-Spilkommen** [comment]
Restart fixes problem and the trash bin Icon I'd forgotten about re-appears :)

**Comment by holgerkpedersen** [comment]
Yeah. sometimes the IU elements are not showing, and sometimes they are shown wrong places. Welcome to the world of User Interfaces 😄. 
I guess, the real issue is; why does the Trash Bin disappear?

**Comment by holgerkpedersen** [comment]
Can this be closed? The functionality is there, but the button was missing.  Could be acheived by workaround. Simply restart the client.

**Comment by jjos2372** [comment]
Apparently this is no longer an issue, please reopen if needed.
