### ISSUE TITLE
BurstNode.java: Exception in line 232. Trying to access trades[0]

### ISSUE THREAD

**Issue by holgerkpedersen** [btdex/btdex#113]
I added a test for length here. If there is a delay before trades array is fully loaded; it shouldn't be possible to access data from the data structure. 

![image](https://user-images.githubusercontent.com/1609665/90000334-52c0f480-dc90-11ea-96cd-00b83e9b86c9.png)

The funny thing is that the data will become available after a short while. Is there a secure way in Java to check; if all the data have been loaded into trades array?

**Comment by holgerkpedersen** [comment]
Further readings:
https://stackoverflow.com/questions/27774706/delay-to-get-data-from-service-to-avoid-null-pointer

**Comment by jjos2372** [comment]
Probably better to just handle it with:
```
if(trades != null && trades.length > 0){
```

**Comment by holgerkpedersen** [comment]
I think it's better to cope with it as an Asynchronous Task. 

But, since it is a 1 second timer, there's a chance to get it right next time the timer runs.
In case the "trades" variable is not null and the length is greater than zero; just terminate the TimerTask.run() as quickly as possible.

Resolved by Pull Request #114

**Comment by jjos2372** [comment]
Yes, I merged #114 but had to change it a bit after. We still need to store the offers, etc. even if we have no trades. It is all merged on the master branch now as we are close to the next release.
