### ISSUE TITLE
Trash Bin active on TRT is an error.

### ISSUE THREAD

**Issue by holgerkpedersen** [btdex/btdex#115]
I have TOOL token on the list.

I tried the following to get a trash bin on TRT Token

Start Client
Select SWAPS
Select any earlier added Burst Token/Asset
Select Add...
Cancel "Add Token" Dialog.

![image](https://user-images.githubusercontent.com/1609665/90062861-a2330f00-dce8-11ea-85fb-1ab7606c6958.png)

After Cancel. TRT will be set in focus. And the trash bin is still there.

**Comment by jjos2372** [comment]
Good catch, just reproduced it. We need to fix it.
