### ISSUE TITLE
BTDEX tries to secure an account, as if it was brand new, when using an unsynced node

### ISSUE THREAD

**Issue by benthetechguy** [btdex/btdex#119]
I run a local node, and the blockchain data was accidentally deleted, so I had to resync it from scratch. When I launched BTDEX, it was previously configured to run on that local node, so when it logged into my BURST account during startup, it saw my BURST address as brand new since the wallet was unsynced, so it tried to do the initial "securing transaction" it usually does, and it gave an error 400 since the node couldn't handle that. BTDEX should check if a node is valid before it's done launching so this doesn't happen. If this happens, maybe it could prompt the user to select a different node from the default list or enter their own so the wallet can launch properly.

**Comment by jjos2372** [comment]
The new automatic node selection should handle this better.
