### ISSUE TITLE
Messages should be public/private and shown in the Details

### ISSUE THREAD

**Issue by frankTheTank72** [btdex/btdex#12]
If a user send Burst or Tokens he/she can add a message.
![image](https://user-images.githubusercontent.com/39116221/71737319-9bd7dd00-2e53-11ea-8d09-ce9ed09b1bc7.png)

We should add a flag here if the message should be encrypted ( i would set it by default to encrypted)

A message sysmbol should be set beside a Transaction Detail to check the message ( if Exits)
![image](https://user-images.githubusercontent.com/39116221/71737391-cf1a6c00-2e53-11ea-95c3-300423e1ecc7.png)

**Comment by jjos2372** [comment]
Default to encrypted is a possible problem when sending to exchanges, as they need an unencrypted routing message.

**Comment by EvolverDE** [comment]
<img width="441" alt="Clipboarder 2020 01 03-004" src="https://user-images.githubusercontent.com/30400562/71737922-5d432200-2e55-11ea-98d5-def8c6828ada.png">

**Comment by frankTheTank72** [comment]
> Default to encrypted is a possible problem when sending to exchanges, as they need an unencrypted routing message.

yes good point … so minimum a flag to choose

**Comment by EvolverDE** [comment]
do we want to "sending to (central) exchanges" per default, or "sending encrypted bank info to seller" per default?

**Comment by jjos2372** [comment]
The encrypted messages will not be handled *manually*, so no need to worry about it. When chatting with the other party or mediators, messages are encrypted by default. When the system sends sensitive information it will also be encrypted. When sending an amount or tokens we will leave they not encrypted so there is less risk of having them not identified by exchanges.

So I'm closing this for now. Open the issue again later if you find this would be needed.
