### ISSUE TITLE
Branch newUI: Token Names disapears; when the default node is not running; and not coming back after establishing a node connection.

### ISSUE THREAD

**Issue by holgerkpedersen** [btdex/btdex#120]
Here is a sample of missing names of tokens already registered after the following:
1. Start BTDEX
2. Change node to running local wallet node
3. Stop the wallet node.
4. Exit BTDEX
5. Start BTDEX
6. Look at the token market. Empty names
7. Change node to other running wallet node
8. Look at the token market. Still Empty names. 

![image](https://user-images.githubusercontent.com/1609665/90955613-33d81480-e47f-11ea-9b42-1793a909ff62.png)

Make sure, the Token Market Dropdown is updated with the names of the tokens!

**Comment by benthetechguy** [comment]
This also happens when using an unsynced node (#119)

**Comment by holgerkpedersen** [comment]
I'm not sure what happens to an unsynced node, @benthetechguy.  It's complicated. 

Unsynced nodes have not exchanged data to and from the public chain. That's why it's called unsynced; I guess. 

If BTDEX relies on an unsynced node, BTDEX tries to communicate with it, to get the needed data and eventually to deliver data. Only known data can be delivered. 

What I see from the debug console is a lot of calls to the selected node; but it's not getting the needed node connection. Many things happens in timer calls on different threads, it seems to rely on the node being available. I hope @jjos2372  could take a look into a way to test for the lack of the node, to avoid the unnecessary calls from when the node is not responding - because the node is down. When this happens, it should be possible to either let the user select another node from the list of known nodes; or let the system decide which node to use (requiring a list of known nodes to iterate through)

**Comment by benthetechguy** [comment]
Yes, in the mentioned issue I said maybe we should have BTDEX check the validity of a node before proceeding to load and if it's unsynced or unreliable (less than 75% uptime or something) notify the user to select a different node.

**Comment by holgerkpedersen** [comment]
I can only agree.

**Comment by holgerkpedersen** [comment]
Perhaps also check to add a check for each of the nodes up status could make the number of nodes on the list smaller; when the user should select. Making it more likely to succeed.

**Comment by benthetechguy** [comment]
Yeah maybe instead of a set list of nodes, BTDEX could have a dynamic list of the best nodes at the time of launch
There's also a nice chart on the [explorer](https://explorer.burstcoin.network/?action=network_status) that shows the best nodes every hour
