### ISSUE TITLE
Can't transfer assets when in Transactions tab

### ISSUE THREAD

**Issue by benthetechguy** [btdex/btdex#121]
In the recent UI update, the button to send assets/tokens to another BURST account was moved to be next to the price and the token selector. The only problem is that if I go into the transactions tab, the asset transfer is no longer there, since it was moved to a different place. Maybe when someone goes into the transaction tab, the asset function could be moved to where it used to be next to the "send BURST" button.

**Comment by jjos2372** [comment]
This was by design. Since we handle multiple tokens, the user must be with a particular token selected to send. So they can be sent only on the token swap tab.
