### ISSUE TITLE
Trades not sorted by date / wrong last price BURST/BTC

### ISSUE THREAD

**Issue by frankTheTank72** [btdex/btdex#124]
Seems the trades are not sorted by  date/time in the transaction histroy - in the graph it seems to be correct.
Also the last price is shown 47sats but it was 33 sats.

![grafik](https://user-images.githubusercontent.com/39116221/93010870-3d8dfd00-f591-11ea-83b8-5a7cb783e0ad.png)

Using btdex v0.3

**Comment by jjos2372** [comment]
Thanks for reporting, I noticed it recently and fixed on 06376ce435fc7d0b0e418117b882bc76a580652d, it will be on the next release:
![image](https://user-images.githubusercontent.com/31958515/93017672-e2640680-f5a0-11ea-8efa-cae6275cde18.png)
