### ISSUE TITLE
java.lang.UnsupportedOperationException: TRANSLUCENT translucency is not supported

### ISSUE THREAD

**Issue by llybin** [btdex/btdex#13]
Full log: https://gist.github.com/llybin/c71517cb2e254b4a89539e58bc5ef6c2

v0.1.8

java 13.0.1 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)

Archlinux KDE

**Comment by jjos2372** [comment]
This is probably a Java version issue, can you please test with Java 8 or another version. This is also probably the reason you are not seeing most of the messages the App should show to you.

**Comment by llybin** [comment]
I've checked on 8 and 11 versions, same error and no hints..

**Comment by llybin** [comment]
https://www.google.com/search?q=java.lang.UnsupportedOperationException%3A+TRANSLUCENT+translucency+is+not+supported.

**Comment by jjos2372** [comment]
I see this `TRANSLUCENT` exception is the problem why you don't see any of the BTDEX messages. Apparently this is an issue with some Linux distros (not Ubuntu).

We are using this effect to show messages and you are no seeing them. We probably need a workaround it here: https://github.com/btdex/btdex/blob/aac1aa318e24acb1c61b47d02c45486a64e73fab/src/main/java/btdex/ui/Toast.java#L20 

Most of the issues you created are related to this problem (you don't see the messages).

**Comment by jjos2372** [comment]
Please check if the latest master version fixes your problem.

Thanks in advance.

**Comment by llybin** [comment]
Solved, thx!
