### ISSUE TITLE
Since version 0.4 my Burst balance shows as 0

### ISSUE THREAD

**Issue by joostschouten** [btdex/btdex#143]
Since version v0.4 my Burst balance shows as 0. I logged off, deleted my config file and logged in again but same issue. Phoenix and on chain all shows a balance.

I'm on a mac.

<img width="227" alt="Screenshot 2021-04-02 at 11 03 44" src="https://user-images.githubusercontent.com/198939/113358911-24209700-93a3-11eb-83d8-3fce91408420.png">

**Comment by jjos2372** [comment]
That is unexpected, maybe connectivity issues with the node or something specific for mac. If you want to share your address privately with me on discord, I can check if I can reproduce it here.

**Comment by joostschouten** [comment]
Just DM'ed you on discord.

**Comment by jjos2372** [comment]
Thanks again for reporting, will be fixed on next release.
