### ISSUE TITLE
Order Book indicates security deposit percentage as a truncated value (rounds down)

### ISSUE THREAD

**Issue by smdhome** [btdex/btdex#145]
The BTDEX order book displays the security deposit percentage as a truncated whole number rather than rounding.  
Example: The Maker places and order to buy 60000 burst and sets the security deposit to 7% (4200).  Due to contract gas fees, the actual security deposit becomes 4199.984565 or 6.9999%.  The order book will display the security deposit percentage on this order as "6%".  The Taker will be required to make the correct security deposit of 4199.984565 though.
![image](https://user-images.githubusercontent.com/500858/113454850-361c2d00-93d7-11eb-9a18-498c039238d1.png)

**Comment by jjos2372** [comment]
Thanks for reporting, will be on the next release.
