### ISSUE TITLE
Changed number of CPU for mining from 1 to 2, now it doesn't work

### ISSUE THREAD

**Issue by paulpoco** [btdex/btdex#146]
When I start BTDEX up it never pops up to display.  I go in tray and select show/hide display and this is what shows only.  No mining, no tranactions.
![image](https://user-images.githubusercontent.com/801414/113462488-f739a780-93d5-11eb-8127-01f5d798ab5e.png)

**Comment by paulpoco** [comment]
Can make it work again by deleting the line for mining CPU amount in config.properties file.

**Comment by jjos2372** [comment]
Thanks for reporting, it should be fixed on the code. I'll make a new release with it.
