### ISSUE TITLE
Connectivity issues that I have never had before.

### ISSUE THREAD

**Issue by paulpoco** [btdex/btdex#147]
Connectivity issues that I have never had before.
![image](https://user-images.githubusercontent.com/801414/114205666-63089c80-990f-11eb-93b1-8c08fbb5e2c9.png)

**Comment by Nivok-Spilkommen** [comment]
Not a connectivity issue, BTDEX by default wakes up the drives every 2 mins. That used to be 4 mins by default with the original scavenger installation.

**Comment by paulpoco** [comment]
Does this mean it is not actually mining?

**Comment by paulpoco** [comment]
> Not a connectivity issue, BTDEX by default wakes up the drives every 2 mins. That used to be 4 mins by default with the original scavenger installation.

Not worried about HDD wake up

**Comment by Nivok-Spilkommen** [comment]
Everything is fine, it just 'pings' the hard-drive to stop it spinning down.

**Comment by paulpoco** [comment]
![image](https://user-images.githubusercontent.com/801414/114206503-4456d580-9910-11eb-9fac-7bd107155cea.png)

**Comment by Nivok-Spilkommen** [comment]
I missed that bit, yeah looks like a connectivity issue.

**Comment by paulpoco** [comment]
I didn't see that yesterday or in the last week

**Comment by paulpoco** [comment]
If I am running a Node what do I change this to:
node=https\://wallet.burstcoin.ro\:443

**Comment by jjos2372** [comment]
We are having some issues with the default node, we will have more nodes soon. And yes, you can run your own and change it by clicking on it.

**Comment by jjos2372** [comment]
We have now a list of updated nodes, use the one closer to you.
