### ISSUE TITLE
Wrong available balance calculation

### ISSUE THREAD

**Issue by llybin** [btdex/btdex#15]
I can't set second order. Nothing happen, no errors(only this https://github.com/btdex/btdex/issues/13) in log after click on button. I've recheck my PIN.

![image](https://user-images.githubusercontent.com/5445357/71766041-242ab080-2f2e-11ea-8965-65189ef28ea1.png)

**Comment by llybin** [comment]
I canceled first order successfully. But can't set new one... after click nothing happens.

I can't set this order, but looks like funds enough:

![image](https://user-images.githubusercontent.com/5445357/71766204-e6c72280-2f2f-11ea-921b-f8b2178bd39c.png)

But 200 TRT he allowed me, transaction 4723025695952141924

![image](https://user-images.githubusercontent.com/5445357/71766208-ed559a00-2f2f-11ea-9644-78225119accf.png)

**Comment by llybin** [comment]
@jjos2372 could you please check, I don't see hints because of bug, but looks strange, why I can't make order?

![image](https://user-images.githubusercontent.com/5445357/71770596-fa3eb180-2f60-11ea-8376-7eefe717bf8c.png)

**Comment by llybin** [comment]
I understood problem, the mistake in current balance in btdex, https://explorer.burst.devtrue.net/address/8087908814943479341
I have only 3 burst, 7 locked.

**Comment by llybin** [comment]
https://github.com/llybin/burst_explorer/blob/10b34b7e22e1cd4d9463fecd7275b962c95fe9b1/scan/templates/accounts/detail.html#L62

**Comment by llybin** [comment]
How you can reproduce it: buy something in market, your funds will locked, because seller not confirmed delivery.

**Comment by jjos2372** [comment]
OK, we were only assuming the amount locked in previous bids/asks and ignoring Burst funds locked on *market*. We need to include that.
