### ISSUE TITLE
Windows 10 ERROR: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed 

### ISSUE THREAD

**Issue by Penultimo** [btdex/btdex#158]
Hello, I received this error while plotting and mining. I install BTDEX on the fresh Windows 10 with latest Java on the other PC, but this error still remain. How can I solve it?
![error](https://user-images.githubusercontent.com/47538574/118608654-99fd8800-b7c2-11eb-9eb2-31524404b017.png)

**Comment by McNose** [comment]
I got the same error here on a similar Win10 system. Yesterday it worked all fine.
I just deleted the config.properties, but with no luck.
The error remains.

Thanks for helping.

**Comment by frankTheTank72** [comment]
Please switch the node from the menu - takes a minute or so ...
We will inform you when the problem is solved again

**Comment by McNose** [comment]
Works fine. Thank you.

**Comment by jjos2372** [comment]
Hello, this was a temporary issue with the europe node. I'm closing this, please reopen if the issue persists to you.
