### ISSUE TITLE
Not fully commited in BURST mining

### ISSUE THREAD

**Issue by Penultimo** [btdex/btdex#164]
![BTDEX not commited](https://user-images.githubusercontent.com/47538574/119246512-dba77d80-bb8a-11eb-9d1b-bc91f1e2ee0f.png)

I commited 19300 BURST, how you see, but in section "Daily rewards estimation per TiB" value of commited BURST not constant and change during the day. Right now it is 9.223, but before couple of hours it was 14000, and so on. 

The same number is displayed in the pool statistics. 
![2021-05-23 05 54 51 pool burstcoin ro c79b6fdfbc2e](https://user-images.githubusercontent.com/47538574/119246637-cc74ff80-bb8b-11eb-8d38-356110f9b715.jpg)
Consequently, I'm not getting what I should be getting. 

How correct this situation?

**Comment by jjos2372** [comment]
Hello, there are two different concepts here. The total amount committed is one thing and is fixed. What we call "commitment" is given **per TiB**. And the chain can only estimate how many TiBs you have as you forge blocks. So yes, they fluctuate over time.

Remember the boost you **should** be getting is given by the amount you committed divided the amount of TiBs you are effectively mining.

If this answers your question please close the issue, if not, please comment further.
