### ISSUE TITLE
After install BTDEX can't create wallet

### ISSUE THREAD

**Issue by alex1v1adamov** [btdex/btdex#168]
Ubuntu 20.04 
openjdk version "16.0.1"

after install BTDEX - can't pass wallet initialization with some GUI problems (see attachment)

![Снимок экрана от 2021-05-30 13-00-12](https://user-images.githubusercontent.com/21301716/120100221-340ceb00-c148-11eb-98af-bbce4e4bd044.png)

when i try to
` java -jar btdex-all-v0.4.11.jar`

i get the same with this stacktrace:
[burst_stacktrace.txt](https://github.com/btdex/btdex/files/6566028/burst_stacktrace.txt)

Lighter themes from ubuntu general settings doesn't help.

**Comment by jjos2372** [comment]
Hello, thank you for reporting. Please try openjdk 8 or 11 which are the versions we currently support.

**Comment by alex1v1adamov** [comment]
> Hello, thank you for reporting. Please try openjdk 8 or 11 which are the versions we currently support.

Thank you for your sopport. Yes, downgrading to java8 resolve the issue.
