### ISSUE TITLE
Unable to switch back to valid node after invalid node has been used

### ISSUE THREAD

**Issue by jurver98** [btdex/btdex#169]
Hi,

Version 0.4.11
btdex-all-v0.4.11.jar
```
root@debian:~/btdex# java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.11+9-post-Debian-1deb10u1, mixed mode, sharing)
```

When changing to a invalid node from btdex, say for example: https://test.com. The application returns the following error (as expected)

[node update] ERROR btdex.core.BurstNode - Exception com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $

However changing back to a working node from the drop down list does not work. The application keeps reporting the same error even though the node is functioning correctly.

At first start:
![Screenshot from 2021-06-02 19-41-48](https://user-images.githubusercontent.com/59688335/120527433-9bda6480-c3da-11eb-9c3b-f3c613b7737b.png)

Changing to a invalid node:
![Screenshot from 2021-06-02 19-42-55](https://user-images.githubusercontent.com/59688335/120527552-bd3b5080-c3da-11eb-8132-8bda816a2234.png)

Changing back to a node from the dropdown list:
![Screenshot from 2021-06-02 19-39-13](https://user-images.githubusercontent.com/59688335/120527259-6cc3f300-c3da-11eb-9423-bf6d1782e74d.png)

In order to clear this failure a known working node has to be chosen and the application has to be restarted.

**Comment by jjos2372** [comment]
Node handling was changed on 38551b956ff797be247f2a0c7dcd3e2c781da112 with the default of automatic node selection.
