### ISSUE TITLE
A click on logo doesn't open site

### ISSUE THREAD

**Issue by llybin** [btdex/btdex#17]
![image](https://user-images.githubusercontent.com/5445357/71766100-eed29280-2f2e-11ea-9b47-c5b34e0f7e44.png)

v0.1.8

java 13.0.1 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)

Archlinux KDE

**Comment by llybin** [comment]
![image](https://user-images.githubusercontent.com/5445357/71892398-609f1c00-317b-11ea-9bbf-9ee543b0ab6d.png)

0.1.10

**Comment by llybin** [comment]
https://www.google.com/search?q=java+the+browse+action+is+not+supported+on+the+current+platform

**Comment by jjos2372** [comment]
Apparently we don't have much option if the platform do not support this action. Any other suggestion before closing it? Apparently only Gnome and KDE are supported.

**Comment by llybin** [comment]
https://stackoverflow.com/a/18004334/1596741 - is not solution?

**Comment by jjos2372** [comment]
Sorry, I missed that. Let's include it soon.

**Comment by llybin** [comment]
I trying to find other solution, I will text here in any case. Solution from stackoverflow looks like hack, but may be really everyone do like that...

**Comment by llybin** [comment]
Strange, why Oracle still not solved it. I've not checked, but search says if I will install libgnome package Desktop will available. But not everyone have Gnome, how about MacOS users also. Second solution on stackoverflow, most links lead there. And found one more solution:  https://github.com/fathominfo/processing-p5js-mode/commit/743432b05e92a7f5aea566005b1be9c020c1adc3

**Comment by jjos2372** [comment]
Have you tested if the latest commit solves your problem? I accidentally (automatically) closed this by the commit message.

**Comment by llybin** [comment]
https://github.com/processing/processing/blob/master/app/src/processing/app/Platform.java

**Comment by llybin** [comment]
trying to build and get error: https://stackoverflow.com/questions/58958890/could-not-determine-java-version-from-13-0-1

**Comment by llybin** [comment]
I will open other issue about it, with java 8 in process

**Comment by llybin** [comment]
Link was opened in browser by xdg-open. Before that, I see errors: https://gist.github.com/llybin/dbd24996852ce9b976a6ae931a364a18
1. mute it?

2. I have the latest KDE 5, in kde 5 name of util: kde-open5 that why he couldn't find it...
Let's change it on:
```java
            if (runCommand("kde-open5", "%s", what)) return true;
            if (runCommand("gnome-open", "%s", what)) return true;
            if (runCommand("xdg-open", "%s", what)) return true;
```

**Comment by jjos2372** [comment]
Reopening to investigate the better alternative.

**Comment by llybin** [comment]
Most linux distos have `xdg-open` in `xdg-utils` package.

I propose to leave only him and indicate in README about `xdg-utils` package need.

**Comment by llybin** [comment]
System.getenv("XDG_CURRENT_DESKTOP")

echo $XDG_CURRENT_DESKTOP
KDE - kde-open5

GNOME - for Gnome - gnome-open

else: xdg-open

**Comment by jjos2372** [comment]
I already have muted all the noise related to this. So, can we remove the entire class https://github.com/btdex/btdex/blob/master/src/main/java/btdex/ui/DesktopApi.java and revert it back to the `java.awt.Desktop` as long as the user has `xdg-open` on the system?

**Comment by llybin** [comment]
No, xdg-open needed for https://github.com/btdex/btdex/blob/master/src/main/java/btdex/ui/DesktopApi.java#L61

I'm for remove these lines, because we wrote in readme about xdg-utils and usually this package is installed.

```
if (runCommand("kde-open", "%s", what)) return true;
if (runCommand("gnome-open", "%s", what)) return true;
```

leave only `if (runCommand("xdg-open", "%s", what)) return true;`

and unmute errors, if user doesn't read manual he will see error and will install xdg-utils package.
