### ISSUE TITLE
Native packaging

### ISSUE THREAD

**Issue by boner-cmd** [btdex/btdex#177]
Enhancement

1. Use jdeps to find only required modules for execution
2. Use jlink to strip the newest working JDK down to just what is required
3. Use [jpackage ](https://openjdk.java.net/jeps/392) to pack it into distributions 

Desired outcome: users never have to download JDK/JRE or report compatibility issues again because btdex will come with all dependencies included.

I've done the jdeps and jlink part for Minecraft before, and the JDK can get stripped pretty far. For btdex, we're talking about potentially doubling the application's size or less. Goal would be to run the first two steps and see if we could keep the final product under 150 MB.

Here's an example of the jlink code I used for Minecraft, it's from a Docker image but you can get the idea:

`RUN ["/opt/java/openjdk/bin/jlink", "--compress=2", "--bind-services", \
  "--strip-debug", "--module-path", "/opt/java/openjdk/jmods", \
  "--add-modules", \
	"java.base,java.compiler,java.desktop,java.logging,java.management,java.naming,java.rmi,java.scripting,java.sql,java.xml,jdk.sctp,jdk.unsupported,java.instrument", \
  "--no-header-files", "--no-man-pages", "--output", "/jlinked"]`

I haven't updated that image since JDK 16, but the entire image was just under 54 MB. If btdex has fewer dependencies, and I expect it would, the JDK could be even smaller.

If required I could do the GitHub action to strip the JDK automatically. I'm not sure about the jdeps step since I know there was a little bit of trial and error there, but I can certainly script the rest of it all up, if that would be easier. Then you could just have the stripped JDK dropped in to a folder in the GitHub repo and you could add the jpackage part to whatever existing building or deployment actions you have.

Of all the PR's I've submitted that "I can do" and then stalled out / been busy, I've done [literally this](https://github.com/boner-cmd/JLinkMC) before so the only part I'm not familiar with is `jpackage`.

**Comment by jjos2372** [comment]
Thanks for the suggestion, I'll take a look on it.

**Comment by jjos2372** [comment]
A java is now bundled on Linux and Mac packages, only a windows installer or zip with Java is now missing. A draft using nsis for the windows installer was included but still has some issues.

**Comment by boner-cmd** [comment]
How large is the Java bundle? That will let me know if I should make a stripped version or not.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by boner-cmd** [comment]
I took a look at the file, it looks great! You got some really good size reduction!
