### ISSUE TITLE
Change of text for clarity

### ISSUE THREAD

**Issue by PhoenixRx7** [btdex/btdex#178]
The current fee text says 
"No trading fees apply, only a one time 0.06615 SIGNA network fee."
It could be better worded as
"This transaction will have a one time network fee of 0.06615 SIGNA, with no other trading fees applicable"

The general public may not (and need not) know the difference between a network fee, and a trading fee. Should someone come to commence a trade, they first get told there is no fee (yay!) but then there IS a fee (boo!)

The critical element is that there will be a fee charged, which needs to be the primary focus. The explanation can then be made, even if it is superfluous for some.

**Comment by shefass** [comment]
He have in mind SWAPS market a.k.a token market.

2021-07-07, tr, 12:28 PhoenixRx7 ***@***.***> rašė:
