### ISSUE TITLE
Bug with the exchanges.

### ISSUE THREAD

**Issue by MoneyControlStockScraper** [btdex/btdex#181]
There was a seller who listed 20 signa for 0.000002 BTC. 

I tried to send the funds to his btc wallet but i got the error "Transaction could not be broadcast due to dust outputs."

No coins were deducted from my account but i was credited with the signa all the same.

![image](https://user-images.githubusercontent.com/84612798/128126289-0947460e-52c2-4681-a890-2f3ed336550c.png)

Some measures like ensuring that amounts falling under "dust outputs" are not listed on the exchange would be good in order to prevent such occurances.

Thank you

**Comment by jjos2372** [comment]
Hello, the other party was just kind enough to send you the 20 SIGNA even though you failed to send the BTC. This is not actually a bug.

We indeed need to limit the offers for BTC and ETH that can fail for small values.

**Comment by MoneyControlStockScraper** [comment]
i seem to meet many kind people who send me signa through the exchange
