### ISSUE TITLE
fix window height

### ISSUE THREAD

**Issue by rever273** [btdex/btdex#188]
When registering Russian text does not fit into the form at the top and bottom, it would be nice to expand this window, or allow the user to make his own length manually.

![image](https://user-images.githubusercontent.com/77928665/131143260-af80d1ef-3c86-4535-a0c5-c2bb75f92367.png)

**Comment by Nidrop** [comment]
seems ok in new releases

**Comment by jjos2372** [comment]
> seems ok in new releases

thanks, closing.
