### ISSUE TITLE
JRELoadError

### ISSUE THREAD

**Issue by smallyunet** [btdex/btdex#189]
I occur this error while opening it:
<img width="258" alt="Screen Shot 2021-08-30 at 1 55 40 PM" src="https://user-images.githubusercontent.com/20765689/131292094-9c9189a3-6a27-4aa1-a3dc-170d79ae9497.png">

But I have installed Java:

```
smallyu@smallyus-MacBook-Air ~ % java -version
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment Homebrew (build 17+0)
OpenJDK 64-Bit Server VM Homebrew (build 17+0, mixed mode)
smallyu@smallyus-MacBook-Air ~ % 
```

**Comment by jjos2372** [comment]
If you can, please try with a Java version lower than 16 (for instance 11 or 13)

**Comment by smallyunet** [comment]
It same problem when I use Java 11, but I notice the case maybe I use the Apple M1 chip. Any plan support Apple M1?

**Comment by jjos2372** [comment]
Hello, you can also try to run the JAR version.
- download `btdex-v0.5.5-all.jar` from https://github.com/btdex/btdex/releases
- run it from a terminal with `java -jar btdex-v0.5.5-all.jar`

Then let us know if that helps.

**Comment by smallyunet** [comment]
It works, thank you!
