### ISSUE TITLE
Display on tab transactions YOU for mine transactions

### ISSUE THREAD

**Issue by llybin** [btdex/btdex#19]
![image](https://user-images.githubusercontent.com/5445357/71766381-255ddc80-2f32-11ea-9848-4a69b95ee589.png)

**Comment by jjos2372** [comment]
The transactions tab only show transactions for your account. The ACCOUNT on this tab is for the other account (when you receive or send). But indeed, more details for the transactions is needed here.

**Comment by jjos2372** [comment]
Now the transactions tab is a bit more complete. Token transactions show the token amount, messages do not show the amount and so on:
![image](https://user-images.githubusercontent.com/31958515/79084921-d67fca00-7d0c-11ea-8dd5-1a3442e821d2.png)

Please open this issue again if I missed something.
