### ISSUE TITLE
Sell button missing ( native token TRT)

### ISSUE THREAD

**Issue by frankTheTank72** [btdex/btdex#2]
If you are on the token market and your balance in the token is > 0 you should have a sell button in the Header ( like on Burst side to buy the token)

![image](https://user-images.githubusercontent.com/39116221/71449477-70ffd180-274d-11ea-9503-d70dc3542221.png)

**Comment by jjos2372** [comment]
The button with the $ symbol can be used to create both buy and sell orders for the current market. If the current market is TRT, this $ button can be used to place buy and sell orders. Please let me know if this was the issue.

**Comment by frankTheTank72** [comment]
Okay - but then i would propose to change the symbol to B/S for example (best with color Background)

**Comment by jjos2372** [comment]
Thanks for the suggestion, our icons are currently coming from here:
https://fontawesome.com/icons?d=gallery&m=free

Please take a look on the ones available there.

**Comment by frankTheTank72** [comment]
okay i would choose this one :-) 
https://fontawesome.com/icons/cart-plus?style=solid

**Comment by jjos2372** [comment]
Just experimented with your suggestion:
![image](https://user-images.githubusercontent.com/31958515/71452655-9b5d8900-2765-11ea-8da6-f8fb511f3cbd.png)

This is already on github, but let's keep it open for a while if another icon suggestion comes by.

**Comment by shefass** [comment]
I like franks cart icon more

**Comment by jjos2372** [comment]
I also find frank's icon better. However, I'm using the same icon ID and apparently depending on size or computer it renders slightly different.

**Comment by jjos2372** [comment]
Closing as this is fixed.
