### ISSUE TITLE
Display my orders in order book, which still in pending

### ISSUE THREAD

**Issue by llybin** [btdex/btdex#20]
I've created new order, transaction in pending, but I would like to see that in order book.

![image](https://user-images.githubusercontent.com/5445357/71766535-5e4a8100-2f33-11ea-8911-13fc79948ce2.png)

**Comment by jjos2372** [comment]
This was recently fixed and will be available on the next release:

![image](https://user-images.githubusercontent.com/31958515/79084418-01b4ea00-7d0a-11ea-8184-b0d2fd7ebc3b.png)
