### ISSUE TITLE
Change node and do what BTDEX says to do, now no user interface

### ISSUE THREAD

**Issue by paulpoco** [btdex/btdex#206]
Change node and do what BTDEX says to do, it said shutdown, I clicked the BTDEX power icon and started it again, now says it is still running but no user interface.  Icon in tray seems distorted.  This happened once before cannot remember what I did to fix.  Rebooted Win10, nope.
 
![image](https://user-images.githubusercontent.com/801414/139774698-65b3d0e0-a8df-4fe4-b745-b6bea7d87b97.png)

**Comment by paulpoco** [comment]
Ok why cannot BTDEX recover itself?

I had to delete this file and start over.
![image](https://user-images.githubusercontent.com/801414/139777145-1b199e50-946a-4806-9b93-c9accc78e001.png)

**Comment by jjos2372** [comment]
Thanks for reporting, indeed there was a problem If an invalid node URL is entered. For instance, missing "http://" or "https://" prefix. This is fixed now on code and it should be able to recover from invalid URLs. To be available on the next release.
