### ISSUE TITLE
[Bug] Token URLs do not open properly in new Explorer

### ISSUE THREAD

**Issue by paulpoco** [btdex/btdex#209]
[Bug] Token URLs do not open properly in new Explorer, I guess the URLs in BTDEX need a different format.
![image](https://user-images.githubusercontent.com/801414/147024786-72dab2db-c85c-4abe-914d-27edc3a8e333.png)

Current URL format that will not open the main Token page for a particular one:
[https://explorer.signum.network/?action=token_inspect&id=10564927423159412675](https://explorer.signum.network/?action=token_inspect&id=10564927423159412675)

![image](https://user-images.githubusercontent.com/801414/147024387-618bd873-bce2-43aa-ad2e-ce9d1cdbbcf2.png)

Correct format to open Token page in new Explorer:
[https://explorer.signum.network/asset/10564927423159412675](https://explorer.signum.network/asset/10564927423159412675)

**Comment by jjos2372** [comment]
Thanks for reporting, this is now handled (redirected) by the explorer.
