### ISSUE TITLE
Feature Request: Add swap.signa to BTDEX

### ISSUE THREAD

**Issue by Valareos** [btdex/btdex#214]
swap.signa now exists on Hive  https://hive-engine.rocks/tokens/SWAP.SIGNA

There is a 1% fee to withdraw from swap.signa on hive to wsigna on BSC. However, if BTDEX listed swap.signa as its own item, then people will be able to trade directly for it with no hive fees.

Plus, since there is no fees to deposit onto HIVE, its easy for people with wsigna to deposit to swap,.signa to offer to trade.

**Comment by jjos2372** [comment]
Would not make more sense to have HIVE as a pair on BTDEX?

**Comment by Valareos** [comment]
Just checked in on this request, to see message left. Sorry for taking so long to return!

swap.signa now exists on Hive Engine. You can get swap.signa by depositing wsigna via the Binance Smart Chain,

to withdraw swap.signa into wsigna though is a 1% fee.  So, only (mostly) free transfers we got atm is 

Signa <--> WSIGNA -> SWAP.SIGNA

By adding a Swap.Signa/Signa pair, we now can go 

Swap.signa<-->signa<-->wsigna -> swap.signa

It also means to convert signa to any other hive based coin, they have to use the liquidity pool set up on tribal dex, which will help increase trade volume and increase value of signa as a whole

**Comment by rogerwim** [comment]
Yes, adding hive is also a option, it is more work and is indirect, and will allow "slip" if you want swap.signa

**Comment by Valareos** [comment]
swap.signa/swap.hive LP now exists on tribaldex.  To get swap.signa, it can be deposited from wsigna.  however, withdrawing swap.signa back to wsigna is a 1% fee. having a swap.signa/signa pair on BTDex will actually allow the conversion of swap.signa to signa for less fees

**Comment by IRSUP1** [comment]
> Would not make more sense to have HIVE as a pair on BTDEX?

Adding swap signa to btdex and keeping swap signa on hive chain active will give Signum more exposure to those who actively use hivechain. It will be helpful for the project overall.

**Comment by paulpoco** [comment]
@Valareos  I think this is now solved on BTDEX 0.5.15

**Comment by jjos2372** [comment]
Correct, closing.
