### ISSUE TITLE
Solo mining doesn't work

### ISSUE THREAD

**Issue by PSLLSP** [btdex/btdex#218]
btdex 0.5.14 (btdex_0.5.14-1_amd64.deb)

Solo mining was working in 0.5.12 against `signum-node` v3.2.1. I created an issue in the past (#179).

I upgraded sigum-node to v3.3.0. btdex 0.5.12 cannot mine solo anymore. I upgraded btdex to 0.5.14 but I see the same error.

Error is like "Submission not accepted". Message text is that "Missing Passphrase and account passphrase not in solo mining config"

I checked `conf/brs.properties`, I see that passphrase is there (`SoloMiningPassphrases=dozen of secret words are here`)

`btdex` config file `.config/btdex/config.properties` has encrypted key (encPrivKey=fedcba9876543210....)

Any idea why I cannot solo mine? I assume it is related to some change in node v3.3.0...

**Comment by Nivok-Spilkommen** [comment]
With v3.3.0 the configuration is read from conf/node.properties not brs.properties, is this the issue here?

**Comment by PSLLSP** [comment]
Well, `SoloMiningPassphrases=` has to be in `conf/node.properties`, after this ( and other changes to node.properties), I can solo mine. I was not using node.properties...

Configuration moved from file `brs.properties` to `node.properties` in V3.3.0. This is important change and it was not implicitly noted in "release notes". Migration from brs.properties to node.properties is not easy, there are so many changes in these files and side by side comparison fails :-( This important step was not mentioned in the release notes. I assumed that migration of DB is the only important step that is required... I was running my node without node.properties for more than a day and I didn't notice that something is missing, only solo mining from `btdex` was not working...

This short note is on release notes. Is it clear that node.properties replaced brs.properties?
> Optionally, inside the conf folder, make a copy of node-default.properties and name it simply node.properties. Modify its contents to suit your needs.

This simple change means that all tutorials on burst for new users are obsolete, those will not work for v3.3.0+...

**Comment by jjos2372** [comment]
Thanks for reporting, the latest node release nodes refer more explicitly to the `node.properties` file being renamed.
