### ISSUE TITLE
Add text: BTC, ETH trades is coming soon

### ISSUE THREAD

**Issue by llybin** [btdex/btdex#22]
As far as I understand BTC, ETH and others crypto still is not available. Will be nice to see text about it: soon coming or etc. When I choose other market I see empty lists and can't create new order. for user looks like a something doesn't work.

**Comment by frankTheTank72** [comment]
We have already a text 

![image](https://user-images.githubusercontent.com/39116221/71768931-5848a600-2f1b-11ea-8728-d23634260d00.png)

But you mean in this empty area ?

![image](https://user-images.githubusercontent.com/39116221/71768956-7e6e4600-2f1b-11ea-805a-923aafae7b97.png)

**Comment by llybin** [comment]
Like that, yes. But I don't see these hints I think this bug: https://github.com/btdex/btdex/issues/13

**Comment by jjos2372** [comment]
Closing, side effect of #13.
