### ISSUE TITLE
Multi Login handling

### ISSUE THREAD

**Issue by frankTheTank72** [btdex/btdex#23]
BTDEX should be able to handle more accounts for an user.

On top right you should have a dropdown - showing all accounts which are setuped or "add new"
By adding a new account you just run again the onboarding process.
Add config more pubKey/proivateKey pairs to handle that:

pubKey=1...
encPrivKey=1...
pubKey=2...
encPrivKey=2...

**Comment by jjos2372** [comment]
I'm not sure we should add this as it can be confusing for newbies. Advanced users can handle multiple accounts by adding a command line argument like:
`java -jar btdex.jar -f account1.properties`
`java -jar btdex.jar -f account2.properties`

So you can point to a different configuration files for multiple accounts, or simply run the app from different folders for every account.

**Comment by jjos2372** [comment]
With the mining support this would complicate too much the design, so no multi-accounts.
