### ISSUE TITLE
BTDEX uses a localhost Node but BTDEX finishes loading 1st

### ISSUE THREAD

**Issue by paulpoco** [btdex/btdex#234]
BTDEX uses a localhost Node but BTDEX finishes loading 1st on bootup and the Node finishes load longer.

So will BTDEX load the SWAPS tab Market tokens you have manually added eventually or does the local Node need to be fully loaded and running before BTDEX starts?   

Or does it only have once chance to load everything from the Node at start?

**Comment by jjos2372** [comment]
BTDEX will show what the node is telling it. If the node is not 100% sync, the markets will not make sense (for example, the token might not even exist yet).

Bottom line, you need a node 100% sync for it to work. Please reopen if I misunderstood the issue.
