### ISSUE TITLE
BTDEX uses old smart contract fee structure when attempting to register BTDEXsell contract

### ISSUE THREAD

**Issue by smdhome** [btdex/btdex#236]
Attempt to register a 2nd BTDEX sell contract resulted in a error using BTDEX v0.6.1.  This may be the result of BTDEX not being updated to use the new fee structure.
![image](https://user-images.githubusercontent.com/500858/177595501-b7806b9a-de74-4d2c-879c-f0ef2aacc78d.png)

**Comment by jjos2372** [comment]
Should be fixed on the latest release.
