### ISSUE TITLE
BTDEX "Distribute revenue" button excludes tokens locked for sale

### ISSUE THREAD

**Issue by smdhome** [btdex/btdex#239]
When using BTDEX 0.6.3 "Distribute revenue" button to send SIGNA to token holders, tokens that are lock for sale in BTDEX are excluded from the transaction.  
Notes:
1.)  This appeared to work OK when tested using a small distribution but later actual distributions to FZT and BTFGCAKE holders with large amounts of tokens locked for sale were excluded.  It is possible that the behavior of this feature is inconsistent.
2.)  The distribution list presented prior to the distribution does NOT exclude tokens locked for sale.  It appears that this distribution list may not always match the transaction when executed.  If so, this is misleading the user.
3.)  It may be an intended use case to exclude tokens locked for sale from distributions.  However, this is not how dividend distributions worked historically and is probably not the expected behavior.  A check box option to allow distribution to holders of locked tokens (or not) might be acceptable.  But the distribution list should always reflect the pending transaction - even if the check box is changed - prior to clicking OK to send the transaction.

**Comment by paulpoco** [comment]
Please fix to include tokens locked for sale in the distribution.

BTDEX has always worked that tokens locked for sell order are still yours and you always got the dividend payout you were entitled to but now you do not.

**Comment by jjos2372** [comment]
There is now an option to select which kind of distribution one wants to make, will be available shortly.
