### ISSUE TITLE
Update Request: Change spacepool.lmsi.club to pool.btfg.space

### ISSUE THREAD

**Issue by Valareos** [btdex/btdex#246]
Please remove spacepool.lmsi.club and replace with pool.btfg.space.  Thank you

**Comment by paulpoco** [comment]
@jjos2372 @Valareos the port has changed from 80 to 8080

**Comment by Valareos** [comment]
Unfortunately, there was an issue with the server that was only found out today that required a port change for the pool

**Comment by jjos2372** [comment]
I assume I can ignore this as the original port was fixed now.
