### ISSUE TITLE
Create a more beautiful splash screen

### ISSUE THREAD

**Issue by llybin** [btdex/btdex#25]
Archlinux, KDE

version 0.1.10

My experience now: https://yadi.sk/i/6boYF_IX9Jy26A

**Comment by jjos2372** [comment]
Added at least a center icon while loading, making it a *splash-like* screen 699ddf9f5e81e1554c4bdf93f09a9550ce96a84a
![image](https://user-images.githubusercontent.com/31958515/71976325-cf6c8b80-31f4-11ea-9694-704c5ff9d2bd.png)

**Comment by llybin** [comment]
checked, much better, thanks!
