### ISSUE TITLE
Gradle build error with java 11 and 13, Could not determine java version

### ISSUE THREAD

**Issue by llybin** [btdex/btdex#26]
With Java 11 and 13 I get error: Could not determine java version from '13.0.1'

https://stackoverflow.com/questions/58958890/could-not-determine-java-version-from-13-0-1

With Java 8 build success. Need fix it or change manual in README.

**Comment by jjos2372** [comment]
This is a problem with the gradle version we are using. However, if we upgrade the gradle wrapper version we end up facing other problems with some dependencies. So for now Java 8 is actually required to build the sources. However, apparently it runs on more recent version with no problems.

**Comment by llybin** [comment]
ok, README changed, I'm happy, you can close :)
