### ISSUE TITLE
transactions tab, my transactions have always zero burst

### ISSUE THREAD

**Issue by llybin** [btdex/btdex#27]
![image](https://user-images.githubusercontent.com/5445357/72014625-d0ec9100-3292-11ea-990e-4a5558661ee0.png)
![image](https://user-images.githubusercontent.com/5445357/72014686-f5e10400-3292-11ea-822e-3c0a312ac100.png)

**Comment by jjos2372** [comment]
Currently the `AMOUNT` column is showing the actual amount sent by the transaction (bids, asks, etc. actually send 0 BURST). Indeed this needs to be improved, related to #4.

**Comment by llybin** [comment]
Oh, ok, I think this related: https://github.com/burst-apps-team/burstcoin/issues/158
