### ISSUE TITLE
Orderbook view

### ISSUE THREAD

**Issue by frankTheTank72** [btdex/btdex#3]
Independent if we have an internal order for the asset market or a cross-chain oder, the first view on the orderbook should be an aggregated view by price-level and separately for buys and sells.

![image](https://user-images.githubusercontent.com/39116221/71449630-0486d180-2751-11ea-8af4-2ef5c010ddf2.png)

If a user wants to buy or sell he/she should click on an Icon beside the buy or sell price-level and in a new section the detail for those orders are shown. 

If the user has already own orders on a price-level it should be highlighted on the Icon to click

**Comment by frankTheTank72** [comment]
Here a similar view from bisq
![image](https://user-images.githubusercontent.com/39116221/71476109-bbcc2880-27e3-11ea-9338-d884cf640d04.png)

Just instead lisitng the single orders on buy and sell side - we should Aggregate them on price Level on the first place

**Comment by EvolverDE** [comment]
this! _(in red)_

**Comment by jjos2372** [comment]
Also think about allowing the user to sort based on a specific column:
![image](https://user-images.githubusercontent.com/31958515/71764239-eb55f180-2ec3-11ea-9f20-a3f4a91bdf36.png)

**Comment by jjos2372** [comment]
Some improvements on this aac1aa318e24acb1c61b47d02c45486a64e73fab:
![image](https://user-images.githubusercontent.com/31958515/71785095-5eea2280-2fda-11ea-8417-632c406b1b24.png)

**Comment by jjos2372** [comment]
More on this subject on 71490fa3f5954798335b189c1144a0109c92fa6f:
![image](https://user-images.githubusercontent.com/31958515/77776197-698de400-702c-11ea-9361-2f47965e4d03.png)

**Comment by jjos2372** [comment]
Our order book was much improved:
![image](https://user-images.githubusercontent.com/31958515/79084539-b818cf00-7d0a-11ea-9c08-d26558b1478a.png)

Please keep in mind that there is not much send in aggregating orders by price on cross-chain markets (since you need to take a specific order). So let me know if there is something else we should work on, or just close this issue.

**Comment by jjos2372** [comment]
Closing for now as I think we have a reasonable order book as is now.
