### ISSUE TITLE
Add support for opening transactions and accounts on a block explorer

### ISSUE THREAD

**Issue by felixbrucker** [btdex/btdex#30]
## How does the system behave currently?

Currently if one clicks on a transaction (id) or burst account it is copied to the clipboard which is nice, but one still needs to manually open a block explorer site and search for the txid or burst account,

## How should the system behave?

It should be possible to open the transaction or burst account directly on a block explorer.

## How could this be achieved?

One possible way would be a right click menu with an entry to open the tx/account on the block explorer.

**Comment by jjos2372** [comment]
This was recently added on 7373d12df9f68b949d77d35ccda4aaa31cb305c7

User selects on the bottom the preferred explorer (or clipboard copy - as before):
![image](https://user-images.githubusercontent.com/31958515/72206244-216a1700-346a-11ea-8c5b-1d318993808c.png)

After some testing we can close this.

**Comment by felixbrucker** [comment]
Id argue having both copy to clipboard and opening a block explorer link would be ideal

**Comment by jjos2372** [comment]
> Id argue having both copy to clipboard and opening a block explorer link would be ideal

In the current state, there is a *Copy to clipboard* explorer option. I personally don't like right click menu options. Or perhaps we can innovate somehow on this?

**Comment by jjos2372** [comment]
Added a small button for the explorer along with the previous copy to clipboard one:
![image](https://user-images.githubusercontent.com/31958515/72208394-cee82500-3480-11ea-8a2b-2f987aed77cb.png)

The icon selected is also open for debate, we use the free icons from here: https://fontawesome.com/icons?d=gallery&q=navigate&m=free

**Comment by felixbrucker** [comment]
i think thats perfect, as for the icon, maybe something like this: https://fontawesome.com/icons/external-link-alt?style=solid or https://fontawesome.com/icons/link?style=solid ?
