### ISSUE TITLE
Not displaying proper values when cycling between BUY/SELL radio-buttons

### ISSUE THREAD

**Issue by Tek-Mind** [btdex/btdex#44]
In the TRT market, when a user clicks on the "BUY TRT" button, the usual pop-up box with instructions and fields to place your order appears. The instruction says, for example, "You are placing a buy limit order for up to 8'644'290.00 TRT at a price of 0.25 BURST each."

In this pop-up box, if the user changes their mind and wants to sell TRT, they can click on the "Sell TRT for BURST" radio-button. The issue is that now, none of the numerical values change in the pop-up box to reflect SELL prices instead of BUY prices. For example, the instruction above would now say, "You are placing a sell limit order for up to 8'644'290.00 TRT at a price of 0.25 BURST each." The numerical values did not change. 

Recommend displaying the proper numerical values when you cycle between the BUY and SELL radio-buttons.

**Comment by goodplanets** [comment]
The 'BURST [TOTAL]' field in the order window of on chain tokens ( OCTs ) is not interactive.

typically the user will enter their proposed exchange amt in this field and expect the exchange itself to automaticaly calculate the  rest of the of the order total based on the market rate of the asset for them. 

Goodplanet- ' i find this to be a standard practice for online cryptocurrency exchange order windows. '

**Comment by goodplanets** [comment]
In other words, the user would expect to be able to enter the purchase amount and have the quantity updated to reflect the total based on the price per unit

**Comment by jjos2372** [comment]
We no longer have these radio buttons, so this can be closed.
