### ISSUE TITLE
Add copy icon/function when user should deposit coin (like BTC)

### ISSUE THREAD

**Issue by frankTheTank72** [btdex/btdex#48]
To make it save for the user to copy the receiver address we should include a icon into the text to be able to copy or add the receiver address on the top with an icon to copy
![grafik](https://user-images.githubusercontent.com/39116221/79069655-32782d80-7cd0-11ea-96fd-ab8d768133ae.png)

**Comment by jjos2372** [comment]
Perfect, and also try to include a QR code with the address and amount due.

**Comment by jjos2372** [comment]
Let's go with this solution with a copy button as well as QR code:
![image](https://user-images.githubusercontent.com/31958515/79174489-4192d480-7dd1-11ea-9675-51c2fd3dfd88.png)
