### ISSUE TITLE
text "change language" instead "english"

### ISSUE THREAD

**Issue by llybin** [btdex/btdex#49]
There chosen russian language but text says : english, maybe rename "change language"?

![image](https://user-images.githubusercontent.com/5445357/79216673-cc2e0f00-7e77-11ea-94c9-cb9a68d681c3.png)

**Comment by shefass** [comment]
You need to translate this word to "ruski"... I had same problem with
lithuanian translation

2020-04-14, an, 13:47 Lev Lybin <notifications@github.com> rašė:

**Comment by shefass** [comment]
Word 42

2020-04-14, an, 13:51 shefass <shefass@gmail.com> rašė:

**Comment by llybin** [comment]
oh, ok :)
