### ISSUE TITLE
Unexpected logic with ask/bid

### ISSUE THREAD

**Issue by llybin** [btdex/btdex#50]
Click sell TRT for 0.10 each.
In dialog you will see you will sell for 0.10 each TRT
Enter PIN, press OK
After transaction confirmation will sold TRT for 0.18, but not for 0.10 as dialog said.

I think the same case with buying.

![image](https://user-images.githubusercontent.com/5445357/79216896-24fda780-7e78-11ea-81ee-293bda151c07.png)

**Comment by shefass** [comment]
It is "limit order" (I am not trader by I guess it means this
situation), so you buy/sell by best price for you, not to/from exact
order. If there is sell order of 0.08 price and you buy for 0.10, at
first will be taken from 0.08 order...If you sell for 0.2 and there is
buy order for 0.22, you will sell at first for 0.22 and so on

2020-04-14, an, 13:53 Lev Lybin <notifications@github.com> rašė:

**Comment by shefass** [comment]
You are right, maybe we need to add sentence which explains this situation

2020-04-14, an, 14:05 shefass <shefass@gmail.com> rašė:

**Comment by llybin** [comment]
yes it should be limit order, but currently it's like a market order even if you choose/set price.

**Comment by jjos2372** [comment]
We have no control over this for token markets on Burst. Orders are always of **limit** type as explained on the dialog. (see for instance https://www.investopedia.com/terms/b/buy-limit-order.asp). 

For cross-chain markets it will work differently, you will take a specific offer.

**Comment by Nivok-Spilkommen** [comment]
In my opinion, these buttons should be disabled/removed, if the market operates in a different way from the cross chain markets, it makes sense that the interfaces look different to save confusion.

**Comment by jjos2372** [comment]
> In my opinion, these buttons should be disabled/removed, if the market operates in a different way from the cross chain markets, it makes sense that the interfaces look different to save confusion.

Yeah, maybe, their only function now is to *copy* their price.

**Comment by jjos2372** [comment]
Maybe to not disable these buttons at all, we could add a *copy* icon for the token orders and when you click on them you are just duplicating them (to probably alter a bit the price and amount).

**Comment by llybin** [comment]
On this tab no limit orders right? Always sell and buy by market price. I think should be only two buttons on a top buy and sell by market price. What to do with buttons on each row? Need to show user, it's not clickable. Need to play with UI, maybe try to remove color on border of buttons, and make it as text not buttons...

**Comment by jjos2372** [comment]
I think we are having a confusion here, orders are **always limit**, you must allow price editing.

**Comment by llybin** [comment]
if they are limit orders, why I can't buy by concrete price?

**Comment by jjos2372** [comment]
A limit order is a type of order to purchase or sell a token at a specified price or better. For buy limit orders, the order will be executed only at the limit price **or a lower one**, while for sell limit orders, the order will be executed only at the limit price **or a higher one**.

**Comment by frankTheTank72** [comment]
@llybin the bevahiour is correct - you are trying to sell at 01.0 but luckly the market pays more then 0.10 - so for example if all ordes get deleted before your 0.10 limit order reach the orderbook you would stay with your 0.10 limit in the market... with a limit order you get always the best price - if you sell higher down to your limit if you buy lower upt to your limit -  @jjos2372 from my point of view nothing to chnage here beside you can write   instead "at" "up to"  (for buy) and "down to" (for sell)

**Comment by llybin** [comment]
Understood. But if your target audience is not traders, could be same questions :) But it's strange case, I can sell by 0.18, but specially chosen 0.10 Can look that case on exchanges, bittrex for example.

**Comment by frankTheTank72** [comment]
@llybin yes you can click on any order in the orderbook an choose this level as your limit. That why i propose to change the wording instead of "at a price of 0.10 " to "down to a price of 01.0 (or better)"
