### ISSUE TITLE
unclear trade UI buttons

### ISSUE THREAD

**Issue by llybin** [btdex/btdex#51]
We talked with you in DM.

1. make more clear buttons, swap colors or add text buy/sell near
![image](https://user-images.githubusercontent.com/5445357/79217620-5aef5b80-7e79-11ea-865b-2071804261d5.png)

2. probably add separator between buy/sell button for more clear separating parts

3. difficult to see what radio button is active now
![image](https://user-images.githubusercontent.com/5445357/79217783-9a1dac80-7e79-11ea-996f-d623ff795d6c.png)

**Comment by jjos2372** [comment]
Thanks for the suggestions, they were updated to:
![image](https://user-images.githubusercontent.com/31958515/79239664-37132200-7e47-11ea-824b-d0299e2cf070.png)
![image](https://user-images.githubusercontent.com/31958515/79239718-44c8a780-7e47-11ea-8a0d-eeeacbc038ab.png)

**Comment by jjos2372** [comment]
Forgot about separating the bids and asks, will reopen.

**Comment by jjos2372** [comment]
More clear separation about the different types of orders:
![image](https://user-images.githubusercontent.com/31958515/79492470-703dc480-7ff6-11ea-869a-5e9a3ac79a8c.png)

**Comment by llybin** [comment]
Looks cool
