### ISSUE TITLE
Bug: Buy Order list ordering

### ISSUE THREAD

**Issue by joostschouten** [btdex/btdex#58]
There seems to be a bug with the ordering in the Buy order list. See below, I would expect the buy order at price 30 to show below the buy orders at price 100.

<img width="1271" alt="Screenshot 2020-05-07 at 18 57 43" src="https://user-images.githubusercontent.com/198939/81263980-c30a1980-9094-11ea-95d0-bf91b6c76d48.png">

How I got in this state:
- The market had one sell order at price 110
- I was the first to place a buy order in this market and I placed it at price 30
- Later two buy orders at price 100 were added by another user and these showed under mine where I expected them to show up above mine.

**Comment by shefass** [comment]
I think it related to missing implementation of custom tokens in Market class. 
https://github.com/btdex/btdex/blob/master/src/main/java/btdex/core/Market.java
