### ISSUE TITLE
Token added does not persist across application sessions

### ISSUE THREAD

**Issue by joostschouten** [btdex/btdex#64]
to reproduce (OSX - 0.1.17)

- Add Cryptomaps token (id: 3702027329806229573)
- Close and open application because the ..+ option is replaced with Cryptomaps rather than added (bug 1?)
- Add GDP token (id: 11280075245570987091)
<img width="212" alt="Screenshot 2020-05-20 at 12 03 38" src="https://user-images.githubusercontent.com/198939/82390540-16b43400-9a93-11ea-901e-cfb802b86550.png">
- Close application<br/>
- Open application<br/>
- Only Cryptomaps in in my dropdown<br/>

<img width="216" alt="Screenshot 2020-05-20 at 12 04 38" src="https://user-images.githubusercontent.com/198939/82390366-a0afcd00-9a92-11ea-87ba-4623e96d176e.png">

This might be due to local environment and persisting these settings in properties file. Not sure as I don't have easy access to another env.

**Comment by jjos2372** [comment]
Thanks for reporting, please try again with v0.1.21. I could not reproduce the problem here, it might be fixed already.

**Comment by joostschouten** [comment]
I just upgraded to the latest version and it does seem to be fixed indeed. Thanks
