### ISSUE TITLE
Lock file not deleted on abnormal Windows shutdown and it's after effects

### ISSUE THREAD

**Issue by Nivok-Spilkommen** [btdex/btdex#69]
In the Windows 10 environment, abnormal shutdowns occur quite often leaving the BRS lock file in place.  On next start up, BRS will exit after seeing the lock file but the lock file cannot now be deleted because, although BRS has exited the jvm it created is still running and is accessing the lock file.  Only resolution is to shut down the jvm from the task manager to unlock the file.  Once deleted normal operation is restored.

**Comment by Nivok-Spilkommen** [comment]
Sorry, this is a brs issue, @jjos, that's why I said I'd do it later, not fully awake yet :)

**Comment by jjos2372** [comment]
Wrong repository for the issue.
