### ISSUE TITLE
Bitcoin Bech32 addresses are shown as invalid on the "Account" screen.

### ISSUE THREAD

**Issue by barton2526** [btdex/btdex#83]
Bech32 addresses begin with "bc1..." and "As of June 2020 Bech32 is supported in many popular wallets and is the preferred address scheme. " (https://en.bitcoin.it/wiki/Bech32)

Bitcoin has 3 address types: https://en.bitcoin.it/wiki/Address

**Comment by jjos2372** [comment]
Thanks for reporting, this should be fixed on the current code.
