### ISSUE TITLE
Reset/Forget Pin Button & Settings

### ISSUE THREAD

**Issue by milkmoney364** [btdex/btdex#9]
Currently a user must delete the .conf file manually in order to "log out" or start fresh. Adding a Settings tab for a Reset Pin and Forget/Clear Account.  Possibly down the road theme changes (dark/light), graph types, node selection, etc. could be housed under Settings.

**Comment by jjos2372** [comment]
Node selection is here already bed12582908253b20cb2a7893dec0a50252c7cd2

**Comment by jjos2372** [comment]
Dark/light themes is also on #31. Reset PIN and sign out were recently added 5c791c63eab9bc9358a3520ffe640484c3ad89a2
