### ISSUE TITLE
Add warning when attempting to trade more coins than in balance.

### ISSUE THREAD

**Issue by benthetechguy** [btdex/btdex#90]
Currently if you try to revise an order, with the way the smart contracts are programmed, on cross-chain trading, changing the price will change the total amount, even to the point where it can exceed the user's balance of the coin. There should be a warning that the changes are impossible with the user's current balance, or if possible, the Smart Contracts could be edited to allow the index currency to be revised.

**Comment by jjos2372** [comment]
What coin are we talking about here? If is the coin on the other chain, we have no control over the users' balance and no way to warn if the user is out of balance or not. The updated conditions are very clear and the user is already accepting he/she would be able to make the transfer.

Please clarify or close the issue.

**Comment by benthetechguy** [comment]
It could be either coin. If the BURST required exceeds the user's balance, there could be a warning. If it's the other coin, we could have functionality in place where it checks the balance of the user's specified account through an explorer or something. If this couldn't be set up, there could just be a warning every time one revises an order about how sometimes the total volume of the order can be unintentionally be changed, sometimes exceeding how much the user is willing to put on the table, and maybe even exceeds their balance.

**Comment by jjos2372** [comment]
It cannot be BURST, the amount in BURST needed is already on the contract.

Regarding the other coin, we cannot check it, it can be anywhere, on multiple wallets, on a centralized exchange, etc.
