### ISSUE TITLE
UNIT RATE FINDER IS LIMITED TO 8 DECIMALS 

### ISSUE THREAD

**Issue by goodplanets** [btdex/btdex#92]
unit rate field in the maker contract will not allow for a 9th digit unit rate or beyond.

non fungible token unit rates will have 9 decimal point unit rates when they are valued above 1 burst.

**Comment by jjos2372** [comment]
Yes, all logic is limited to 8 decimal places as nearly all tools in the space. Token prices are also limited on the blockchain itself, so no point on this.
