### ISSUE TITLE
Design incongruency - logic inversion from the norm

### ISSUE THREAD

**Issue by goodplanets** [btdex/btdex#95]
I lack the terminology to say what i mean so i must use visual aid.

eterbase for example but all exchanges are merging into this UI

market - market data - order window
![image](https://user-images.githubusercontent.com/40472463/88461389-9d590900-ce68-11ea-912d-c2db5ea3adbc.png)
-
![image](https://user-images.githubusercontent.com/40472463/88461402-aea21580-ce68-11ea-8770-220de5e057dc.png)

On eterbase and other exchanges the data is presented in a congruent pattern. like this.

Market  
Sale currency / Index currency
BURST / ETH

Market data - measured in the Index currency

Market window - 
buy / sell
unit rate 
amt to sell
total cost

BTDEX on the other hand has an inversion in the logic in the market window

market - market data - order window
![image](https://user-images.githubusercontent.com/40472463/88462052-3cccca80-ce6e-11ea-94c7-c8d972ce50bd.png)

Market - market data
btdex markets are selected by the drop down currency selector - thats fine
btdex does not offer in app market data however we assume the volume would be tallied in BURST

Order window-
this is where the logic deviates from the norm. here have a comparison.
![image](https://user-images.githubusercontent.com/40472463/88462275-c9c45380-ce6f-11ea-9e4c-6dd896e59730.png)

it has been repeated to me that the nature of the burst protocol pins the sum of burst to the smart contract.

i believe it can be possible to pin the sum of the burst contract while deriving the total cost by pricing the coin for sale in BURST instead of the coin for sale which is inverted logic from the normal order creation window.

**Comment by benthetechguy** [comment]
I can't tell if this is a UI issue or a smart contract issue

**Comment by goodplanets** [comment]
> 
> 
> I can't tell if this is a UI issue or a smart contract issue

i'd reserve comments for devs ben however i think this is a UI issue because i beleive it is possible to create the proper congruency by simply flipping the entry forms like shown above however i'm not sure that's true because i'm not familiar with the actual burstcoin protocol.

**Comment by goodplanets** [comment]
https://www.investopedia.com/terms/r/reciprocal-currency.asp
Reciprocal Currency Definition
By Chris B. Murphy
Updated May 28, 2019
What Is Reciprocal Currency?

revised by GP - instead of dollar i put BURST and instead of other currency i put another crypto to make def work for us.

In the foreign exchange market, a reciprocal currency is when a currency pair involves BURST but the BURST is not the base currency. A reciprocal currency is also quoted as dollars per unit of currency instead of in units of currency per dollar.
The Basics of a Reciprocal Currency

There are currency pairs where the BURST is the base currency like the BURST/BTC or the BURST versus the BTC or the BURST/ETH, which is the BURST versus the ETH.

However, reciprocal currencies are quoted in what's commonly referred to as "European" terms meaning the currency other than the BURST is the base currency.

Real World Examples of a Reciprocal Currency

The currency pair ETH/BURST has the BURST as its base currency and the BURST as its quote currency. Reciprocal currency describes currency pairs used in the foreign exchange market where the BURST and another currency are paired, but where the USD is not the first currency quoted. In other words, one would quote the exchange rate of ETH/BURST as the ETH versus BURST.

**Comment by goodplanets** [comment]
when working with reciprocals it's important to keep the congruity of the base currency inline with the side of the market the window represents.

for example 

BTC - BURST  on Bittrex has an order window that sets the base currency as BTC

BURST - BTC on BTDEX has an order window that too sets the base currency as BTC

this incongruity may cause great confusion or cause entities like coin market cap to not recognize BTDEX.

**Comment by goodplanets** [comment]
![image](https://user-images.githubusercontent.com/40472463/88463017-6d643280-ce75-11ea-8c13-bf7e451ab96f.png)

**Comment by frankTheTank72** [comment]
In btdex v0.3 the view changed to this :
![grafik](https://user-images.githubusercontent.com/39116221/93010924-d91f6d80-f591-11ea-8f6a-9cb5d9ac1616.png)

Maybe it is now more clear , or not ?
