### ISSUE TITLE
Change wording on "sign out" button

### ISSUE THREAD

**Issue by benthetechguy** [btdex/btdex#98]
The "sign out" button in the bottom right of the BTDEX client can be confusing to new users. Aljo on the discord server was having problems with his config being "deleted" because he was using the "sign out" button to exit BTDEX. If the text on the button was changed to be something like "clear config", this problem wouldn't happen in the future for new users.

**Comment by shefass** [comment]
I agree and this option must be moved to settings

**Comment by jjos2372** [comment]
We don't have a "settings" panel. For now I'm rewording this and changing the button and tittle to "Factory Reset".

**Comment by jjos2372** [comment]
![image](https://user-images.githubusercontent.com/31958515/88546682-1d12df00-cff3-11ea-9b3b-eab5e310d253.png)
